site_name: Schema Gen
site_description: Universal schema converter for Python - define once, generate everywhere
site_url: https://schema-gen.readthedocs.io/
repo_url: https://github.com/jagatsingh/schema-gen
repo_name: jagatsingh/schema-gen

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Schema Format: schema-format.md
  - CLI Reference: cli-reference.md
  - Configuration: configuration.md
  - Examples: examples.md
  - API Reference: api-reference.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: false
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jagatsingh/schema-gen
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/schema-gen/

copyright: Copyright &copy; 2024 Jagat Singh