"""Generator to create Zod schemas from USR schemas"""

import logging
from datetime import datetime
from enum import Enum
from pathlib import Path
from typing import Any

from jinja2 import Template

from ..core.config import Config
from ..core.usr import FieldType, USRField, USRSchema
from .base import BaseGenerator

logger = logging.getLogger(__name__)

# Keys honored from ``Config.zod``. Any other key triggers a warning.
_SUPPORTED_ZOD_CONFIG_KEYS: frozenset[str] = frozenset({"strict", "coerce"})


def _collect_external_schema_refs(schema: USRSchema) -> set[str]:
    """Walk a USR schema and return the set of NESTED_SCHEMA names it
    references that are NOT the schema itself (those are self-refs and
    handled via z.lazy()). Looks through ``inner_type`` (list / set /
    frozenset) and ``union_types`` (tuple / union) so nested container
    types produce imports too.
    """
    refs: set[str] = set()

    def _walk(field: USRField) -> None:
        if field.type == FieldType.NESTED_SCHEMA and field.nested_schema:
            if field.nested_schema != schema.name:
                refs.add(field.nested_schema)
        if field.inner_type is not None:
            _walk(field.inner_type)
        for ut in field.union_types or []:
            _walk(ut)

    for f in schema.fields:
        _walk(f)
    return refs


class ZodGenerator(BaseGenerator):
    """Generates Zod schemas (TypeScript/JavaScript) from USR schemas"""

    index_filename = "index.ts"

    def __init__(self, config: Config | None = None) -> None:
        super().__init__(config=config)
        self.template = Template(self._get_template())
        self._self_ref_schema_names: set[str] = set()
        # Warn on unknown Config.zod keys.
        if config is not None:
            zod_cfg: dict[str, Any] = getattr(config, "zod", None) or {}
            for key in zod_cfg:
                if key not in _SUPPORTED_ZOD_CONFIG_KEYS:
                    logger.warning(
                        "Unknown Config.zod key: %s (supported: %s)",
                        key,
                        sorted(_SUPPORTED_ZOD_CONFIG_KEYS),
                    )

    def _zod_cfg(self) -> dict[str, Any]:
        """Return the ``Config.zod`` dict, or empty dict if not set."""
        if self.config is None:
            return {}
        return getattr(self.config, "zod", None) or {}

    @property
    def file_extension(self) -> str:
        return ".ts"

    @property
    def generates_index_file(self) -> bool:
        return True

    def get_schema_filename(self, schema: USRSchema) -> str:
        return f"{schema.name.lower()}.ts"

    def generate_index(self, schemas: list[USRSchema], output_dir: Path) -> str | None:
        """Generate index.ts content for the zod package.

        Schemas are runtime values (re-exported as values); the inferred
        types are re-exported via ``export type`` so that projects using
        ``verbatimModuleSyntax`` don't trip TS1205 on the type-only names
        (POC finding C5).

        Each name is exported at most once (from the first module that
        declares it) to avoid ``Duplicate identifier`` TS errors when
        multiple schema files reference the same enum.
        """
        lines = [
            "/**",
            " * Generated Zod schemas",
            " * Auto-generated by schema-gen",
            " */",
            "",
        ]

        # Track names already emitted so shared enums are only exported once.
        exported_value_names: set[str] = set()
        exported_type_names: set[str] = set()

        for schema in schemas:
            module = f"./{schema.name.lower()}"
            # Collect runtime (value) names — schemas themselves.
            value_names: list[str] = []
            for e in schema.enums:
                name = f"{e.name}Schema"
                if name not in exported_value_names:
                    value_names.append(name)
                    exported_value_names.add(name)
            schema_val = f"{schema.name}Schema"
            if schema_val not in exported_value_names:
                value_names.append(schema_val)
                exported_value_names.add(schema_val)
            for v in schema.variants:
                variant_val = f"{self._variant_to_schema_name(schema.name, v)}Schema"
                if variant_val not in exported_value_names:
                    value_names.append(variant_val)
                    exported_value_names.add(variant_val)

            # Collect type-only names — inferred TS types.
            type_names: list[str] = []
            for e in schema.enums:
                if e.name not in exported_type_names:
                    type_names.append(e.name)
                    exported_type_names.add(e.name)
            if schema.name not in exported_type_names:
                type_names.append(schema.name)
                exported_type_names.add(schema.name)
            for v in schema.variants:
                variant_type = self._variant_to_schema_name(schema.name, v)
                if variant_type not in exported_type_names:
                    type_names.append(variant_type)
                    exported_type_names.add(variant_type)

            if value_names:
                lines.append(f"export {{ {', '.join(value_names)} }} from '{module}';")
            if type_names:
                lines.append(
                    f"export type {{ {', '.join(type_names)} }} from '{module}';"
                )

        return "\n".join(lines) + "\n"

    def generate_model(self, schema: USRSchema, variant: str | None = None) -> str:
        """Generate a Zod schema for a schema variant

        Args:
            schema: USR schema to generate from
            variant: Specific variant to generate, or None for full schema

        Returns:
            Generated Zod schema code (TypeScript)
        """
        fields = schema.get_variant_fields(variant) if variant else schema.fields

        # Determine the schema name
        schema_name = schema.name
        if variant:
            schema_name = self._variant_to_schema_name(schema.name, variant)

        # Generate field definitions
        field_definitions = []

        for field in fields:
            field_def = self._generate_field_definition(field)
            field_definitions.append(field_def)

        return self.template.render(
            schema_name=schema_name,
            base_schema_name=schema.name,
            variant_name=variant,
            description=schema.description,
            fields=field_definitions,
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
        )

    def generate_all_variants(self, schema: USRSchema) -> dict[str, str]:
        """Generate all variants for a schema

        Args:
            schema: USR schema to generate variants for

        Returns:
            Dictionary mapping variant names to generated code
        """
        variants = {}

        # Generate base schema (all fields)
        variants["base"] = self.generate_model(schema)

        # Generate specific variants
        for variant_name in schema.variants:
            variants[variant_name] = self.generate_model(schema, variant_name)

        return variants

    def generate_file(self, schema: USRSchema) -> str:
        """Generate a complete TypeScript file with all variants for a schema

        Args:
            schema: USR schema to generate from

        Returns:
            Complete file content with all schemas
        """
        # Track self-referencing fields for z.lazy() generation
        self._self_ref_schema_names = (
            {schema.name} if schema.get_self_referencing_fields() else set()
        )

        # Collect cross-schema references so we can emit the right
        # ``import { OtherSchema } from './other';`` lines at the top of
        # the generated file (Copilot POC finding C4).
        external_refs = _collect_external_schema_refs(schema)

        all_schemas = []
        all_types = []

        # Generate base schema
        base_fields = schema.fields
        base_field_defs = []

        for field in base_fields:
            field_def = self._generate_field_definition(field)
            base_field_defs.append(field_def)

        base_schema = self._generate_single_schema(
            schema.name, schema.description, base_field_defs, is_base_schema=True
        )
        all_schemas.append(base_schema)

        # Generate base TypeScript type
        base_type = self._generate_typescript_type(schema.name, base_fields)
        all_types.append(base_type)

        # Generate variants
        for variant_name in schema.variants:
            variant_fields = schema.get_variant_fields(variant_name)
            variant_field_defs = []

            for field in variant_fields:
                field_def = self._generate_field_definition(field)
                variant_field_defs.append(field_def)

            variant_schema_name = self._variant_to_schema_name(
                schema.name, variant_name
            )
            variant_schema = self._generate_single_schema(
                variant_schema_name,
                schema.description,
                variant_field_defs,
                is_base_schema=False,
            )
            all_schemas.append(variant_schema)

            # Generate variant TypeScript type
            variant_type = self._generate_typescript_type(
                variant_schema_name, variant_fields
            )
            all_types.append(variant_type)

        # Generate complete file
        return self._generate_complete_file(
            schema.name,
            all_schemas,
            all_types,
            schema.enums,
            external_refs=external_refs,
        )

    def _generate_field_definition(self, field: USRField) -> str:
        """Generate a single field definition for Zod

        Returns:
            Field definition code
        """
        # Get base Zod type
        zod_type = self._get_zod_type(field)

        # Add validation rules
        validations = []

        if field.type == FieldType.STRING:
            if field.min_length is not None:
                validations.append(f".min({field.min_length})")
            if field.max_length is not None:
                validations.append(f".max({field.max_length})")
            if field.regex_pattern:
                validations.append(f".regex(/{field.regex_pattern}/)")
            if field.format_type == "email":
                validations.append(".email()")
            elif field.format_type == "url":
                validations.append(".url()")
            elif field.format_type == "uuid":
                validations.append(".uuid()")

        elif field.type in [FieldType.INTEGER, FieldType.FLOAT]:
            if field.min_value is not None:
                validations.append(f".min({field.min_value})")
            if field.max_value is not None:
                validations.append(f".max({field.max_value})")

        # Build complete field definition
        field_def = f"  {field.name}: {zod_type}{''.join(validations)}"

        # Add optional if needed
        if field.optional:
            field_def += ".optional()"

        # Add default value
        if field.default is not None:
            if isinstance(field.default, Enum):
                field_def += f'.default("{field.default.value}")'
            elif isinstance(field.default, str):
                field_def += f'.default("{field.default}")'
            else:
                field_def += f".default({str(field.default).lower() if isinstance(field.default, bool) else field.default})"

        # Add trailing comma (required for valid JS/TS in z.object)
        field_def += ","

        # Add description as comment
        if field.description:
            field_def += f" // {field.description}"

        return field_def

    def _get_zod_type(self, field: USRField) -> str:
        """Get the Zod type for a field"""

        if field.type == FieldType.STRING:
            return "z.string()"

        elif field.type == FieldType.INTEGER:
            return "z.number().int()"

        elif field.type == FieldType.FLOAT:
            return "z.number()"

        elif field.type == FieldType.BOOLEAN:
            return "z.boolean()"

        elif field.type == FieldType.DATETIME:
            if self._zod_cfg().get("coerce", False):
                return "z.coerce.date()"
            return "z.string().datetime()"

        elif field.type == FieldType.DATE:
            if self._zod_cfg().get("coerce", False):
                return "z.coerce.date()"
            return "z.string().date()"

        elif field.type == FieldType.TIME:
            if self._zod_cfg().get("coerce", False):
                return "z.coerce.date()"
            return "z.string().time()"

        elif field.type == FieldType.UUID:
            return "z.string().uuid()"

        elif field.type == FieldType.LIST or field.type in (
            FieldType.SET,
            FieldType.FROZENSET,
        ):
            if field.inner_type:
                inner_zod_type = self._get_zod_type(field.inner_type)
                return f"z.array({inner_zod_type})"
            else:
                return "z.array(z.any())"

        elif field.type == FieldType.TUPLE:
            if field.union_types:
                inner_types = [self._get_zod_type(ut) for ut in field.union_types]
                return f"z.tuple([{', '.join(inner_types)}])"
            else:
                return "z.tuple([])"

        elif field.type == FieldType.DICT:
            if field.inner_type is not None:
                value_zod_type = self._get_zod_type(field.inner_type)
                return f"z.record({value_zod_type})"
            return "z.record(z.any())"

        elif field.type == FieldType.UNION:
            if field.union_types:
                union_types = [self._get_zod_type(ut) for ut in field.union_types]
                return f"z.union([{', '.join(union_types)}])"
            else:
                return "z.any()"

        elif field.type == FieldType.LITERAL:
            if field.literal_values:
                literals = [
                    f'z.literal("{v}")' if isinstance(v, str) else f"z.literal({v})"
                    for v in field.literal_values
                ]
                if len(literals) == 1:
                    return literals[0]
                else:
                    return f"z.union([{', '.join(literals)}])"
            else:
                return "z.string()"

        elif field.type == FieldType.ENUM:
            return f"{field.enum_name}Schema" if field.enum_name else "z.string()"

        elif field.type == FieldType.NESTED_SCHEMA:
            # For self-referential schemas, use z.lazy() to avoid circular references
            if (
                hasattr(self, "_self_ref_schema_names")
                and field.nested_schema in self._self_ref_schema_names
            ):
                return f"z.lazy(() => {field.nested_schema}Schema)"
            # For nested schemas, reference the schema by name
            return f"{field.nested_schema}Schema"

        else:
            return "z.any()"

    def _variant_to_schema_name(self, schema_name: str, variant_name: str) -> str:
        """Convert variant name to PascalCase schema name"""
        parts = variant_name.split("_")
        variant_pascal = "".join(word.capitalize() for word in parts)
        return f"{schema_name}{variant_pascal}"

    def _generate_single_schema(
        self,
        schema_name: str,
        description: str,
        field_defs: list[str],
        is_base_schema: bool = False,
    ) -> str:
        """Generate a single Zod schema definition"""
        lines = []

        if description:
            lines.append("/**")
            lines.append(f" * {description}")
            lines.append(" */")

        lines.append(f"export const {schema_name}Schema = z.object({{")

        for field_def in field_defs:
            lines.append(field_def)

        strict = self._zod_cfg().get("strict", False)
        closing = "}).strict();" if strict else "});"
        lines.append(closing)

        return "\n".join(lines)

    def _generate_typescript_type(
        self, schema_name: str, fields: list[USRField]
    ) -> str:
        """Generate TypeScript type definition"""
        return f"export type {schema_name} = z.infer<typeof {schema_name}Schema>;"

    def _get_typescript_type(self, field: USRField) -> str:
        """Get TypeScript type for a field (for type generation)"""

        if field.type == FieldType.STRING:
            return "string"
        elif field.type == FieldType.INTEGER or field.type == FieldType.FLOAT:
            return "number"
        elif field.type == FieldType.BOOLEAN:
            return "boolean"
        elif field.type in (FieldType.DATETIME, FieldType.DATE, FieldType.TIME):
            if self._zod_cfg().get("coerce", False):
                return "Date"
            return "string"
        elif field.type == FieldType.UUID:
            return "string"
        elif field.type == FieldType.LIST or field.type in (
            FieldType.SET,
            FieldType.FROZENSET,
        ):
            if field.inner_type:
                inner_type = self._get_typescript_type(field.inner_type)
                return f"{inner_type}[]"
            else:
                return "any[]"
        elif field.type == FieldType.TUPLE:
            if field.union_types:
                inner_types = [
                    self._get_typescript_type(ut) for ut in field.union_types
                ]
                return f"[{', '.join(inner_types)}]"
            return "[]"
        elif field.type == FieldType.DICT:
            return "Record<string, any>"
        elif field.type == FieldType.UNION:
            if field.union_types:
                union_types = [
                    self._get_typescript_type(ut) for ut in field.union_types
                ]
                return " | ".join(union_types)
            else:
                return "any"
        elif field.type == FieldType.LITERAL:
            if field.literal_values:
                values = [
                    f'"{v}"' if isinstance(v, str) else str(v)
                    for v in field.literal_values
                ]
                return " | ".join(values)
            else:
                return "string"
        elif field.type == FieldType.ENUM:
            return field.enum_name or "string"
        elif field.type == FieldType.NESTED_SCHEMA:
            return field.nested_schema
        else:
            return "any"

    def _generate_complete_file(
        self,
        schema_name: str,
        schemas: list[str],
        types: list[str],
        enums: list = None,
        external_refs: set[str] | None = None,
    ) -> str:
        """Generate complete TypeScript file with header, imports, and all schemas"""
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")
        enums = enums or []
        external_refs = external_refs or set()

        lines = [
            "/**",
            " * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY",
            f" * Generated from: {schema_name}",
            f" * Generated at: {timestamp}",
            " * Generator: schema-gen Zod generator",
            " *",
            " * To regenerate this file, run:",
            " *     schema-gen generate --target zod",
            " *",
            " * Changes to this file will be overwritten.",
            " */",
            "",
            "import { z } from 'zod';",
        ]

        # Cross-file imports for nested schema references (POC finding C4).
        # We only import the runtime Zod schema (value).  The inferred TS
        # types are derived via ``z.infer<typeof …Schema>`` so a separate
        # ``import type`` is unnecessary and triggers TS6133 when
        # ``noUnusedLocals`` is enabled (#38).
        for ref in sorted(external_refs):
            if ref == schema_name:
                continue  # self-ref is handled via z.lazy()
            module = ref.lower()
            lines.append(f"import {{ {ref}Schema }} from './{module}';")

        lines.append("")

        # Add enum definitions before schemas
        for enum_def in enums:
            values = ", ".join(f'"{v}"' for _name, v in enum_def.values)
            lines.append(f"export const {enum_def.name}Schema = z.enum([{values}]);")
            lines.append(
                f"export type {enum_def.name} = z.infer<typeof {enum_def.name}Schema>;"
            )
            lines.append("")

        # Add schemas
        for i, schema in enumerate(schemas):
            if i > 0:
                lines.append("")
            lines.append(schema)

        lines.append("")

        # Add TypeScript types
        for type_def in types:
            lines.append(type_def)

        return "\n".join(lines)

    def _get_template(self) -> str:
        """Get the Jinja2 template for Zod schemas"""
        return """/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: {{ base_schema_name }}{% if variant_name %} ({{ variant_name }} variant){% endif %}
 * Generated at: {{ timestamp }}
 * Generator: schema-gen Zod generator
 *
 * To regenerate this file, run:
 *     schema-gen generate --target zod
 *
 * Changes to this file will be overwritten.
 */

import { z } from 'zod';

{%- if description %}
/**
 * {{ description }}
 */
{%- endif %}
export const {{ schema_name }}Schema = z.object({
{%- for field_def in fields %}
{{ field_def }}
{%- endfor %}
});

export type {{ schema_name }} = z.infer<typeof {{ schema_name }}Schema>;"""
